
package org.openerproject.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OpenerServiceImplService", targetNamespace = "http://remoteservice.vicomtech.org/", wsdlLocation = "file:/C:/Users/yo/Desktop/git_repos/target-properties/src/main/resources/opener-analysis-service.wsdl")
public class OpenerServiceImplService
    extends Service
{

    private final static URL OPENERSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.openerproject.ws.client.OpenerServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.openerproject.ws.client.OpenerServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/yo/Desktop/git_repos/target-properties/src/main/resources/opener-analysis-service.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/yo/Desktop/git_repos/target-properties/src/main/resources/opener-analysis-service.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        OPENERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public OpenerServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OpenerServiceImplService() {
        super(OPENERSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://remoteservice.vicomtech.org/", "OpenerServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns OpenerService
     */
    @WebEndpoint(name = "OpenerServiceImplPort")
    public OpenerService getOpenerServiceImplPort() {
        return super.getPort(new QName("http://remoteservice.vicomtech.org/", "OpenerServiceImplPort"), OpenerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OpenerService
     */
    @WebEndpoint(name = "OpenerServiceImplPort")
    public OpenerService getOpenerServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://remoteservice.vicomtech.org/", "OpenerServiceImplPort"), OpenerService.class, features);
    }

}
